### ISSUE TITLE
pecl install jsonnet  error

### ISSUE THREAD

**Issue by zhouruhong** [Neeke/Jsonnet-PHP#1]
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.4.0
checking host system type... x86_64-apple-darwin15.4.0
checking target system type... x86_64-apple-darwin15.4.0
checking for PHP prefix... /usr/local/Cellar/php56/5.6.19
checking for PHP includes... -I/usr/local/Cellar/php56/5.6.19/include/php -I/usr/local/Cellar/php56/5.6.19/include/php/main -I/usr/local/Cellar/php56/5.6.19/include/php/TSRM -I/usr/local/Cellar/php56/5.6.19/include/php/Zend -I/usr/local/Cellar/php56/5.6.19/include/php/ext -I/usr/local/Cellar/php56/5.6.19/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php56/5.6.19/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/Cellar/php56/5.6.19/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for jsonnet support... yes, shared
make: `libjsonnet.so' is up to date.
checking for jsonnet files in default path... not found
configure: error: Please reinstall the jsonnet distribution

**Comment by zhouruhong** [comment]
OSX 10.11.4  php 5.6.19

**Comment by Neeke** [comment]
copy that

**Comment by Neeke** [comment]
Fixed with 1.1.0
