### ISSUE TITLE
jsonnet.so load failed  

### ISSUE THREAD

**Issue by zhouruhong** [Neeke/Jsonnet-PHP#2]
Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php56/5.6.19/lib/php/extensions/no-debug-non-zts-20131226/jsonnet.so' - dlopen(/usr/local/Cellar/php56/5.6.19/lib/php/extensions/no-debug-non-zts-20131226/jsonnet.so, 9): Library not loaded: libjsonnet.so
  Referenced from: /usr/local/Cellar/php56/5.6.19/lib/php/extensions/no-debug-non-zts-20131226/jsonnet.so
  Reason: image not found in Unknown on line 0

**Comment by Neeke** [comment]
Fixed with 1.1.0
